// Generated by Wrangler on Sun May 26 2024 14:14:29 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	VITE_AUTH_SERVICE_URL: string;
	VITE_COMMENT_SERVICE_URL: string;
	VITE_VOTE_SERVICE_URL: string;
	VITE_CLIENT_DOMAIN: string;
	AUTH_SERVICE_URL: string;
	COMMENT_SERVICE_URL: string;
	VOTE_SERVICE_URL: string;
	CLIENT_DOMAIN: string;
}
